-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;

DROP TABLE IF EXISTS public.app_user CASCADE;
CREATE TABLE IF NOT EXISTS public.app_user
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    username character varying(255) COLLATE pg_catalog."default" NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (username)
);

DROP TABLE IF EXISTS public.store CASCADE;
CREATE TABLE IF NOT EXISTS public.store
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(255) NOT NULL,
    UNIQUE (name),
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.product CASCADE;
CREATE TABLE IF NOT EXISTS public.product
(
    id bigint NOT NULL,
    product_name character varying(255) NOT NULL,
    package_unit character varying(255) NOT NULL,
    product_category character varying(255) NOT NULL,
    brand character varying(255) NOT NULL,
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.product_store CASCADE;
CREATE TABLE IF NOT EXISTS public.product_store
(
    store_id bigint NOT NULL,
    product_id bigint NOT NULL,
    package_quantity double precision,
    price double precision,
    updated_at date NOT NULL,
    PRIMARY KEY (store_id, product_id, updated_at)
);

DROP TABLE IF EXISTS public.discount CASCADE;
CREATE TABLE IF NOT EXISTS public.discount
(
    store_id bigint NOT NULL,
    product_id bigint NOT NULL,
    from_date date NOT NULL,
    to_date date NOT NULL,
    percentage double precision,
    PRIMARY KEY (store_id, product_id, from_date)
);

DROP TABLE IF EXISTS public.shopping_list CASCADE;
CREATE TABLE IF NOT EXISTS public.shopping_list
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    user_id bigint NOT NULL,
    created_at date NOT NULL,
    name character varying(255) NOT NULL,
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.shopping_list_item CASCADE;
CREATE TABLE IF NOT EXISTS public.shopping_list_item
(
    shopping_list_id bigint NOT NULL,
    product_id bigint,
    PRIMARY KEY (shopping_list_id, product_id)
);

DROP TABLE IF EXISTS public.price_alert CASCADE;
CREATE TABLE IF NOT EXISTS public.price_alert
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    user_id bigint NOT NULL,
    product_name character varying(255) NOT NULL,
    target_price double precision NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.product_store
    DROP CONSTRAINT IF EXISTS storeproducts_store_fk;

ALTER TABLE IF EXISTS public.product_store
    ADD CONSTRAINT storeproducts_store_fk FOREIGN KEY (store_id)
    REFERENCES public.store (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

ALTER TABLE IF EXISTS public.product_store
    DROP CONSTRAINT IF EXISTS storeproducts_products_fk;

ALTER TABLE IF EXISTS public.product_store
    ADD CONSTRAINT storeproducts_products_fk FOREIGN KEY (product_id)
    REFERENCES public.product (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

ALTER TABLE IF EXISTS public.discount
    DROP CONSTRAINT IF EXISTS discounts_storeproducts_composite_fk;

ALTER TABLE IF EXISTS public.discount
    ADD CONSTRAINT discounts_store_fk FOREIGN KEY (store_id)
    REFERENCES public.store (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

ALTER TABLE IF EXISTS public.discount
    ADD CONSTRAINT discounts_products_fk FOREIGN KEY (product_id)
    REFERENCES public.product (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

ALTER TABLE IF EXISTS public.shopping_list
    DROP CONSTRAINT IF EXISTS shopping_list_to_user_fk;

ALTER TABLE IF EXISTS public.shopping_list
    ADD CONSTRAINT shopping_list_to_user_fk FOREIGN KEY (user_id)
    REFERENCES public.app_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

ALTER TABLE IF EXISTS public.shopping_list_item
    DROP CONSTRAINT IF EXISTS listitem_to_list_fk;

ALTER TABLE IF EXISTS public.shopping_list_item
    ADD CONSTRAINT listitem_to_list_fk FOREIGN KEY (shopping_list_id)
    REFERENCES public.shopping_list (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

ALTER TABLE IF EXISTS public.shopping_list_item
    DROP CONSTRAINT IF EXISTS listitem_to_product_fk;

ALTER TABLE IF EXISTS public.shopping_list_item
    ADD CONSTRAINT listitem_to_product_fk FOREIGN KEY (product_id)
    REFERENCES public.product (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

ALTER TABLE IF EXISTS public.price_alert
    DROP CONSTRAINT IF EXISTS alert_user_fk;

ALTER TABLE IF EXISTS public.price_alert
    ADD CONSTRAINT alert_user_fk FOREIGN KEY (user_id)
    REFERENCES public.app_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;